name: k8s-cluster-stig-baseline
title: Kubernetes 1.16 Based upon Kubernetes 1.16 Security Technical Implementation Guideline (STIG) 
maintainer: DISA DevSecOps Team 
copyright: Defense Information Systems Agency (DISA)
license: Apache-2.0
summary: InSpec testing for baseline compliance with the Kubernetes STIG
description: An InSpec profile verifying compliance with Kubernetes STIG version 1.16 
version: 1.0.1
inspec_version: ">= 4.0"
supports:
- platform: k8s

depends:
- name: inspec-k8s
  url: https://github.com/bgeesaman/inspec-k8s/archive/0.1.3.tar.gz

inputs:
  - name: k8s_minium_version
    description: 'Minimum version of Kubernetes deployment'
    type: string
    value: 'v1.19.5'
    required: true
